services:
  bird:
    build:
      context: ./bird
      dockerfile: Dockerfile
    image: bird-api
    ports:
      - "4201:4201"
    networks:
      - birdnet

  birdImage:
    build:
      context: ./birdImage
      dockerfile: Dockerfile
    image: bird-api
    ports:
      - "4200:4200"
    networks:
      - birdnet

networks:
  birdnet:
    driver: bridge
